### ISSUE TITLE
Numpy not avalible error

### ISSUE THREAD

**Issue by tin2tin** [tin2tin/text_to_video#1]
This error is connected to the modelscope install process. It seems like pytorch 2 and numpy is incompatible with Python 3.10 and it must be downgraded to 3.9 - which means Blender 3.0 must be used(Blender 3.1 upgraded to python 3.10)
https://github.com/openai/whisper/discussions/1032

**Comment by YACO99** [comment]
Ubuntu 23.04
Python 3.11.4
Blender 3.4
Solution command: `sudo pip install numpy`
False solution command: `pip install numpy`
